# Generated by Django 5.2.8 on 2025-11-29 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=5)),
                ('raza', models.CharField(blank=True, default='Mestizo', max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('edad_anos', models.IntegerField(verbose_name='Edad (años aproximados)')),
                ('tamano', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], max_length=1)),
                ('descripcion', models.TextField(help_text='Historia, personalidad y necesidades de la mascota.')),
                ('imagen_principal', models.ImageField(help_text='Foto principal de la mascota.', upload_to='mascotas_fotos/')),
                ('estado_adopcion', models.CharField(choices=[('D', 'Disponible'), ('P', 'En Proceso'), ('A', 'Adoptado')], default='D', max_length=1)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
