# Generated by Django 5.2.8 on 2025-11-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='imagen_principal',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='edad_anos',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('JOVEN', 'Joven'), ('ADULTO', 'Adulto')], default='JOVEN', max_length=10, verbose_name='Edad de la Mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='region',
            field=models.CharField(choices=[('PANAMA', 'Panamá'), ('PANAMA_OESTE', 'Panamá Oeste'), ('COLON', 'Colón'), ('LOS_SANTOS', 'Los Santos'), ('COCLE', 'Coclé'), ('VERAGUAS', 'Veraguas'), ('DARIEN', 'Darién'), ('CHIRIQUI', 'Chiriquí'), ('HERRERA', 'Herrera'), ('BOCAS_DEL_TORO', 'Bocas del Toro'), ('COMARCA', 'Comarca Indígena')], default='PANAMA', max_length=20, verbose_name='Provincia/Región'),
        ),
    ]
