# Generated by Django 5.2.8 on 2025-11-30 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_solicitudadopcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(choices=[('C', 'Cachorro (0-1 año)'), ('J', 'Joven (1-7 años)'), ('A', 'Adulto (+7 años)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado_adopcion',
            field=models.CharField(choices=[('D', 'Disponible'), ('P', 'Pendiente de adopción'), ('A', 'Adoptado')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=6),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas_fotos/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='publicado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_publicadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='region',
            field=models.CharField(choices=[('Panamá', 'Panamá'), ('Panamá Oeste', 'Panamá Oeste'), ('Colón', 'Colón'), ('Los Santos', 'Los Santos'), ('Coclé', 'Coclé'), ('Veraguas', 'Veraguas'), ('Darién', 'Darién'), ('Chiriquí', 'Chiriquí')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_whatsapp', models.CharField(blank=True, help_text='Tu número de teléfono para ser contactado por WhatsApp (ej: 5076xxxxxx)', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
