# Generated by Django 5.2.8 on 2025-12-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_mascota_descripcion_alter_mascota_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, choices=[('NEGRO', 'Negro'), ('BLANCO', 'Blanco'), ('ATIGRADO', 'Atigrado'), ('CAFE', 'Café/Marrón'), ('GRIS', 'Gris'), ('OTRO', 'Otro/Variado')], default='OTRO', max_length=50),
        ),
    ]
