# Generated by Django 5.2.8 on 2025-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='', upload_to='mascotas_fotos/'),
            preserve_default=False,
        ),
    ]
