# Generated by Django 5.2.8 on 2025-12-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('ADOPCION', 'Adopción de Mascotas'), ('PERROS', 'Cuidado de Perros'), ('GATOS', 'Cuidado de Gatos')], default='ADOPCION', max_length=50)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('descripcion_corta', models.TextField(help_text='Máximo 300 caracteres para la vista previa.', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
