# Generated by Django 5.2.8 on 2025-12-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
